image: dbogatov/docker-containers:jekyll-latest

stages:
- build
- test
- release
- deploy

build:
  stage: build
  script:
  - ./build.sh
  artifacts:
    expire_in: 30 min
    paths:
    - _site/
  tags:
  - docker

tidy:
  stage: test
  dependencies:
  - build
  before_script:
  - http-server _site/ -p 8080 > /dev/null &
  - sleep 5
  script:
  - curl -Ls http://localhost:8080 | tidy -e
  tags:
  - docker
  
blc:
  stage: test
  dependencies:
  - build
  before_script:
  - http-server _site/ -p 8080 > /dev/null &
  - sleep 5
  script:
  - blc --filter-level 3 --input http://localhost:8080 -rog --exclude www.nginx.com
  tags:
  - docker

dockerify:
  stage: release
  dependencies:
  - build
  script:
  - docker build -t registry.dbogatov.org/dbogatov/my-blog .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/dbogatov/my-blog
  tags:
  - shell
